- task: Prisma Cloud IaC Scan@2
  inputs:
    Path: '.'
    prismaCloudService: 'Prisma IaC CS'
    High: '0'
    Medium: '0'
    Low: '0'
    Operator: 'or'
    Tags: 'env=CS, team=GLR, phase=testing'